go: &go
  image: golang
  working_dir: /go/src/github.com/bemobi/migrate
  volumes:
    - $GOPATH:/go
go-test:
  <<: *go
  command: sh -c 'go test -v ./...'
  links:
    - postgres
postgres:
  image: postgres
